Add firebase tools to gitignore
MvRemmerden/gitpod pull request #3
Opened 2023-03-24 10:47 UTC by MvRemmerden

## Description

## Related Issue(s)

Fixes #

## How to test

## Release Notes

```release-note
```

## Documentation

## Werft options:

- [ ] /werft with-local-preview
      If enabled this will build `install/preview`
- [ ] /werft with-preview
- [ ] /werft with-large-vm
- [ ] /werft with-integration-tests=all
      Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

2023-03-24 22:17 UTC, MvRemmerden commented on .gitignore
> +.firebase-tools
```suggestion
.firebase-toolssss
```

2023-03-25 09:11 UTC, mvanremmerden requested changes
Test

2023-03-25 09:11 UTC, mvanremmerden commented on .gitignore
```suggestion
Test
```

2023-03-25 09:11 UTC, mvanremmerden commented on .gitignore
>  .idea/misc.xml
```suggestion
.idea/misc.xmllll
```

2023-03-25 12:14 UTC, mvanremmerden requested changes

2023-03-25 12:14 UTC, mvanremmerden commented on .gitignore
>  # Jetbrains workspace files
```suggestion
# Jetbrainsy workspace files
```

2023-03-25 20:09 UTC, mvanremmerden approved these changes

2023-03-25 21:06 UTC, mvanremmerden requested changes
Fix this stupid stuff

2023-03-25 21:07 UTC, merged

2023-03-26 10:52 UTC, mvanremmerden reviewed
Test

2023-03-26 10:52 UTC, mvanremmerden commented on .gitignore
Test